/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/5/g/geopher/perl-5.36.0/miniperl ../bin/enc2xs -Q -O -o symbol_t.c -f symbol_t.fnm
 enc2xs VERSION 2.24
*/
extern encode_t AdobeSymbol_encoding;
extern encode_t AdobeZdingbat_encoding;
extern encode_t MacDingbats_encoding;
extern encode_t MacSymbol_encoding;
extern encode_t dingbats_encoding;
extern encode_t symbol_encoding;
