/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/5/g/geopher/perl-5.36.0/miniperl ../bin/enc2xs -Q -o ma_05_t.c -f ma_05_t.fnm
 enc2xs VERSION 2.24
*/
extern encode_t MacJapanese_encoding;
